[package]
name = "apdl-poem"
version = "0.1.0"
edition = "2021"

[dependencies]
apdl-core = { path = "../apdl-core" }
nom = "7.1"
regex = "1.0"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]